[package]
name = "satoshi-bridge"
version = "0.9.0"
edition.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.near.reproducible_build]
image = "sourcescan/cargo-near:0.16.0-rust-1.86.0"
image_digest = "sha256:3220302ebb7036c1942e772810f21edd9381edf9a339983da43487c77fbad488"
passed_env = []
container_build_command = [
    "cargo",
    "near",
    "build",
    "non-reproducible-wasm",
    "--locked",
    "--no-abi",
]

[package.metadata.near.reproducible_build.variant.bitcoin]
container_build_command = ["cargo", "near", "build", "non-reproducible-wasm", "--locked", "--no-abi", "--no-default-features", "--features", "bitcoin"]

[package.metadata.near.reproducible_build.variant.zcash]
container_build_command = ["cargo", "near", "build", "non-reproducible-wasm", "--locked", "--no-abi", "--no-default-features", "--features", "zcash"]

[dependencies]
near-sdk.workspace = true
near-contract-standards.workspace = true
bitcoin.workspace = true
hex.workspace = true
near-plugins.workspace = true
omni-utils.workspace = true
k256 = "0.13.1"
ed25519-dalek = "2.1.0"
crypto-shared = { git = "https://github.com/near/mpc_old", rev = "0afee9004a1b1c3386940e60c28cff7cf1b5978c" }
zcash_primitives = { version = "0.24.0", default-features = false, features = ["circuits", "transparent-inputs"], optional = true }
zcash_transparent = { version = "0.4.0", features = ["transparent-inputs"], optional = true }
orchard = { version = "0.11.0", default-features = false, optional = true }
sapling-crypto = { version = "0.5.0", default-features = false, optional = true }
zcash_protocol = { version = "0.6.1" }
core2 = { version = "0.3", optional = true }
zcash_address = { version = "0.9.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.12", features = ["custom"] }

[dev-dependencies]
near-workspaces = { version = "0.20", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
rand = "0.8"
hex = "0.4"
bs58 = "0.5"

[features]
default = []
zcash = ["zcash_primitives", "zcash_transparent", "orchard", "core2", "sapling-crypto"]
bitcoin = []
