name: CI

on:
  push:
    branches:
      - omni-main
  pull_request:

permissions:
  checks: write

jobs:
  rust-checks:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-provider: warpbuild

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings -D clippy::pedantic -D clippy::as_conversions -A clippy::must_use_candidate

      - name: Run tests
        run: cargo test --all -- --nocapture
